name: publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.4.12.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
      - name: Install
        run: opam install . --deps-only
      - name: Build
        run: |
          OCAMLPARAM='_,ccopt=-static' opam exec -- dune build
          mkdir owtools-x86_64-unknown-linux-musl
          cp _build/install/default/bin/{wag,wfind,wlocate} owtools-x86_64-unknown-linux-musl
          tar --zstd -cf owtools-x86_64-unknown-linux-musl{.tar.zst,}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: owtools-x86_64-unknown-linux-musl.tar.zst
          asset_name: owtools-x86_64-unknown-linux-musl.tar.zst
          tag: ${{ github.ref }}
          overwrite: true
