name: publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.4.12.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
      - name: Install
        run: opam install . --deps-only
      - name: Build
        run: |
          OCAMLPARAM='_,ccopt=-static' opam exec -- dune build
          version=$(basename ${{ github.ref }})
          pkg=owtools-${version}-${{ matrix.arch }}
          mkdir ${pkg}
          cp _build/install/default/bin/{wag,wfind,wlocate} ${pkg}
          tar --zstd -cf ${pkg}.tar.zst ${pkg}
          mkdir pack
          mv ${pkg}.tar.zst pack/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pack/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
